import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { Metric } from './mockData';

interface ReportPDFProps {
  title: string;
  dateRange: string;
  narrative: string;
  metrics: Metric[];
  organizationName: string;
  primaryColor: string;
  financials?: {
    program: number;
    admin: number;
    fundraising: number;
  };
}

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
  },
  header: {
    marginBottom: 30,
    borderBottom: 2,
    borderBottomColor: '#059669',
    paddingBottom: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 8,
  },
  dateRange: {
    fontSize: 12,
    color: '#6B7280',
  },
  section: {
    marginTop: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 12,
  },
  narrative: {
    fontSize: 11,
    color: '#374151',
    lineHeight: 1.6,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metricCard: {
    width: '48%',
    padding: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 4,
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#059669',
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 10,
    color: '#6B7280',
  },
  metricType: {
    fontSize: 8,
    color: '#9CA3AF',
    marginTop: 4,
    textTransform: 'uppercase',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9CA3AF',
    textAlign: 'center',
    borderTop: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
});

// Create Document Component
export const ReportPDF = ({
  title,
  dateRange,
  narrative,
  metrics,
  organizationName,
  primaryColor,
  financials,
}: ReportPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.dateRange}>{dateRange}</Text>
      </View>

      {/* Narrative Section */}
      {narrative && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Our Impact Story</Text>
          <Text style={styles.narrative}>{narrative}</Text>
        </View>
      )}

      {/* Metrics Section */}
      {metrics.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Key Metrics</Text>
          <View style={styles.metricsGrid}>
            {metrics.map((metric, index) => (
              <View key={index} style={styles.metricCard}>
                <Text style={styles.metricValue}>
                  {metric.unit === '$' && '$'}
                  {metric.value.toLocaleString()}
                  {metric.unit === '%' && '%'}
                </Text>
                <Text style={styles.metricLabel}>{metric.label}</Text>
                <Text style={styles.metricType}>{metric.type}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Financials Section */}
      {financials && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Financial Allocation</Text>
          <View style={{ marginTop: 8 }}>
            <Text style={{ fontSize: 10, color: '#374151', marginBottom: 4 }}>
              Program Services: {financials.program}%
            </Text>
            <Text style={{ fontSize: 10, color: '#374151', marginBottom: 4 }}>
              Administrative: {financials.admin}%
            </Text>
            <Text style={{ fontSize: 10, color: '#374151', marginBottom: 4 }}>
              Fundraising: {financials.fundraising}%
            </Text>
          </View>
        </View>
      )}

      {/* Footer */}
      <View style={styles.footer}>
        <Text>
          Generated by {organizationName} • Created with Verity Impact Reports
        </Text>
      </View>
    </Page>
  </Document>
);

/**
 * Generate and download a PDF report
 */
export async function generatePDF(props: ReportPDFProps): Promise<void> {
  try {
    console.log('Starting PDF generation with props:', {
      title: props.title,
      metricsCount: props.metrics.length,
      organizationName: props.organizationName
    });

    const blob = await pdf(<ReportPDF {...props} />).toBlob();

    if (!blob) {
      throw new Error('PDF blob generation failed');
    }

    console.log('PDF blob created, size:', blob.size);

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${props.title.replace(/\s+/g, '-').toLowerCase()}.pdf`;
    document.body.appendChild(link); // Add to DOM for better browser compatibility
    link.click();
    document.body.removeChild(link);

    // Cleanup after a short delay to ensure download starts
    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 100);

    console.log('PDF download triggered successfully');
  } catch (error) {
    console.error('Error generating PDF:', error);
    if (error instanceof Error) {
      throw new Error(`Failed to generate PDF: ${error.message}`);
    }
    throw new Error('Failed to generate PDF');
  }
}

/**
 * Generate a shareable PNG image using html2canvas
 */
export async function generatePNG(props: ReportPDFProps): Promise<void> {
  try {
    // Dynamically import html2canvas to avoid bundling issues
    const html2canvas = (await import('html2canvas')).default;

    // Find the preview element to capture
    const previewElement = document.querySelector('[data-report-preview]') as HTMLElement;

    if (!previewElement) {
      throw new Error('Report preview element not found. Please ensure the preview is visible.');
    }

    // Capture the element as canvas
    const canvas = await html2canvas(previewElement, {
      backgroundColor: '#ffffff',
      scale: 2, // Higher quality
      logging: false,
      useCORS: true,
      allowTaint: true,
      imageTimeout: 0,
    });

    // Convert canvas to blob and download - wrap in Promise to properly await
    await new Promise<void>((resolve, reject) => {
      canvas.toBlob((blob) => {
        if (!blob) {
          reject(new Error('Failed to create image blob'));
          return;
        }

        try {
          const url = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.href = url;
          link.download = `${props.title.replace(/\s+/g, '-').toLowerCase()}.png`;
          document.body.appendChild(link); // Add to DOM for Firefox compatibility
          link.click();
          document.body.removeChild(link);
          URL.revokeObjectURL(url);
          resolve();
        } catch (err) {
          reject(err);
        }
      }, 'image/png');
    });
  } catch (error) {
    console.error('Error generating PNG:', error);
    throw new Error('Failed to generate PNG. Make sure the preview is visible and try again.');
  }
}
