import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { Metric } from './mockData';

interface ReportPDFProps {
  title: string;
  dateRange: string;
  narrative: string;
  metrics: Metric[];
  organizationName: string;
  primaryColor: string;
  financials?: {
    program: number;
    admin: number;
    fundraising: number;
  };
}

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
  },
  header: {
    marginBottom: 30,
    borderBottom: 2,
    borderBottomColor: '#059669',
    paddingBottom: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 8,
  },
  dateRange: {
    fontSize: 12,
    color: '#6B7280',
  },
  section: {
    marginTop: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 12,
  },
  narrative: {
    fontSize: 11,
    color: '#374151',
    lineHeight: 1.6,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metricCard: {
    width: '48%',
    padding: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 4,
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#059669',
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 10,
    color: '#6B7280',
  },
  metricType: {
    fontSize: 8,
    color: '#9CA3AF',
    marginTop: 4,
    textTransform: 'uppercase',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9CA3AF',
    textAlign: 'center',
    borderTop: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
});

// Create Document Component
export const ReportPDF = ({
  title,
  dateRange,
  narrative,
  metrics,
  organizationName,
  primaryColor,
  financials,
}: ReportPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.dateRange}>{dateRange}</Text>
      </View>

      {/* Narrative Section */}
      {narrative && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Our Impact Story</Text>
          <Text style={styles.narrative}>{narrative}</Text>
        </View>
      )}

      {/* Metrics Section */}
      {metrics.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Key Metrics</Text>
          <View style={styles.metricsGrid}>
            {metrics.map((metric, index) => (
              <View key={index} style={styles.metricCard}>
                <Text style={styles.metricValue}>
                  {metric.unit === '$' && '$'}
                  {metric.value.toLocaleString()}
                  {metric.unit === '%' && '%'}
                </Text>
                <Text style={styles.metricLabel}>{metric.label}</Text>
                <Text style={styles.metricType}>{metric.type}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Financials Section */}
      {financials && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Financial Allocation</Text>
          <View style={{ marginTop: 8 }}>
            <Text style={{ fontSize: 10, color: '#374151', marginBottom: 4 }}>
              Program Services: {financials.program}%
            </Text>
            <Text style={{ fontSize: 10, color: '#374151', marginBottom: 4 }}>
              Administrative: {financials.admin}%
            </Text>
            <Text style={{ fontSize: 10, color: '#374151', marginBottom: 4 }}>
              Fundraising: {financials.fundraising}%
            </Text>
          </View>
        </View>
      )}

      {/* Footer */}
      <View style={styles.footer}>
        <Text>
          Generated by {organizationName} • Created with Verity Impact Reports
        </Text>
      </View>
    </Page>
  </Document>
);

/**
 * Generate and download a PDF report
 */
export async function generatePDF(props: ReportPDFProps): Promise<void> {
  try {
    const blob = await pdf(<ReportPDF {...props} />).toBlob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${props.title.replace(/\s+/g, '-').toLowerCase()}.pdf`;
    link.click();
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF');
  }
}

/**
 * Generate a shareable PNG image (using html2canvas would be needed for this)
 * For now, we'll just export the PDF
 */
export async function generatePNG(props: ReportPDFProps): Promise<void> {
  // For PNG export, you would typically use html2canvas to capture the preview
  // For now, fall back to PDF
  return generatePDF(props);
}
